# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

  
# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            CellNOpt
tagline:          CellNOpt Documentation
description:      "Identification of signaling models based on perturbation data and prior knowledge"
#url:              http://saezlab.github.io
url:               
site.url:          https://saezlab.github.io
baseurl:          /CellNOptR/
#baseurl:           /CellNOptR
#site.baseurl:           /CellNOptR
toollogo:         /CellNOptR/tool_logo.png

author:
  name:           'Enio Gjerga'

paginate:         5

# Custom vars
version:          1.4.0

github:
  repo:           https://github.com/saezlab/CellNOptR
