# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

  
# Dependencies
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            CellNOpt
tagline:          CellNOpt Documentation
description:      "Identification of signaling models based on perturbation data and prior knowledge"
url:              https://saezlab.github.io
baseurl:          /CellNOptR_packages_archived/
toollogo:         https://saezlab.github.io/CellNOptR_packages_archived/tool_logo.png

author:
  name:           'Enio Gjerga and Attila Gabor'

paginate:         5

# Custom vars
version:          1.4.0

github:
  repo:           https://github.com/saezlab/CellNOptR_packages_archived
